services:
  - type: web
    name: codevault-backend
    env: node
    plan: free
    buildCommand: |
      npm install
      ls -la src/models/  # Debug: List files in models directory
    startCommand: NODE_ENV=production node --es-module-specifier-resolution=node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    envVarGroups:
      - name: production
        envVars:
          - key: NODE_ENV
            value: production
          - key: PORT
            value: 8000 