services:
  - type: web
    name: codevault-backend
    env: node
    plan: free
    buildCommand: |
      npm install
      cp -r src/* .
    startCommand: NODE_ENV=production node --experimental-modules index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true 